### ISSUE TITLE
Maven settings on documentation page doesn't work

### ISSUE THREAD

**Issue by Tgo1014** [synapseslab/android-bluegps-sdk-demoapp#1]
The [documentation item 2.2 ](https://github.com/synapseslab/android-bluegps-sdk-demoapp/blob/main/documentation/bluegps_android_sdk.md#22-adding-the-library-to-an-existing-android-application) says to setup maven repository to fetch the SDK artifact but it fails, leaving me with just the option to copy the `.aar` from the demo project, but this way I would need to manually update the SDK by copying the file every time.

You can see it failed to find the artifact on the specified URL in the image below:

![image](https://user-images.githubusercontent.com/8679058/227584876-8abc22f6-9e7c-40b6-b6a0-a990c317c71f.png)

Is the artifact supposed to be available? 

Thanks!

**Comment by fr4ncesco** [comment]
right now there is a limitation on github that doesn't allow to have maven package available on public channel but only on private one.

We change the repository statically include our SDK library so no need to perform this step.

Anyhow thanks to point out the error on our documentation. 

Will be fixed soon.

**Comment by Tgo1014** [comment]
Thanks for the quick response! No chance of making it available on maven Central? Would be really useful.

**Comment by fr4ncesco** [comment]
Not in plan. 
We are waiting to have the feature on github.
