### ISSUE TITLE
`startNotifyRegionChanges` just return one region tracking

### ISSUE THREAD

**Issue by Tgo1014** [synapseslab/android-bluegps-sdk-demoapp#3]
I'm trying to use `startNotifyRegionChanges(tags: List<String>, regions: List<BGPRegion>, callbackHandler: () -> Unit)` to get current position of a `tag`. I would imagine that, as the `callbackHandler` returns a `Map`, it would indicate in which room the `tag` is currently in, but in reality, it just returns a `Map` with only the first `BGPRegion` that I passed to the `regions` param.

Is this the correct behavior for this method? If so, how can I track the room where the `tag` is currently in in real time?

Thanks!

**Comment by Halulkin** [comment]
Having the same issue. Any news on this?

**Comment by Tgo1014** [comment]
This was solved with the release of 1.4.2. Thanks!
